version: '3'
services:
    promtail:
        container_name: promtail
        volumes:
            - './config:/etc/promtail/'
            - '/var/lib/docker/containers:/var/lib/docker/containers'
            - '/var/run/docker.sock:/var/run/docker.sock'
        environment:
          - CLIENT_URL=${CLIENT_URL:?CLIENT_URL must be set as environment variable}
        image: 'grafana/promtail:2.6.1'
        command: 
        - "-config.expand-env=true"  # to enable bash environment substitution in config file ($VAR)
        - "-config.file=/etc/promtail/config.yml"