server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${CLIENT_URL}

scrape_configs:
  - job_name: docker
    pipeline_stages:
      - docker: {}
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 60s
    relabel_configs:
      - action: replace
        source_labels: ["__meta_docker_container_label_com_docker_compose_service"]
        target_label: app
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container_name'
      - action: replace
        source_labels: ["__meta_docker_container_name"]
        target_label: instance
      - action: replace
        source_labels: ["__meta_docker_container_label_namespace","__meta_docker_container_label_com_docker_compose_service"]
        separator: "/"
        target_label: job
      - action: replace
        source_labels: ["__meta_docker_container_label_namespace"]
        target_label: namespace